spring:
  application:
    name: spring-mongodb
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/products}
app:
  product-data-file: ${PRODUCT_DATA_FILE:classpath:products.json}
server:
  port: ${SERVER_PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs